import cv2
import numpy as np

class EventVisionAdapter:
    """
    Bridges visual observations from accumulated event frames to the SSP-SLAM pipeline.
    It detects structural keypoints using Shi-Tomasi corners from the event-count images, 
    tracks them across frames using Lucas-Kanade optical flow, and extracts ORB appearance descriptors.
    """
    
    def __init__(self, max_landmarks=30, view_radius=3.0, fov_x=60.0, backend='classic'):
        self.max_landmarks = max_landmarks
        self.view_radius = view_radius
        self.fov_x = fov_x # Horizontal Field of View in degrees
        self.backend = backend
        
        # Detector and Extractor
        self.orb = cv2.ORB_create()
        self.feature_params = dict(maxCorners=100, qualityLevel=0.01, minDistance=10, blockSize=7)
        self.lk_params = dict(winSize=(15, 15), maxLevel=2,
                              criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))
        
        self.tracks = []           # List of active tracks: structure: {id: int, p: (u, v)}
        self.next_track_id = 0
        self.prev_gray = None
        
        # Stores history for SLAM array formatting later
        # Format: list of dictionaries mapping track_id -> dict(bearing, vector, descriptor)
        self.history = []
        
    def _get_tracks_arrays(self):
        """Helper to get tracked points as (N, 1, 2) array for optical flow"""
        if not self.tracks:
            return None
        return np.float32([tr['p'] for tr in self.tracks]).reshape(-1, 1, 2)
        
    def detect_and_track_keypoints(self, gray_obs):
        """
        Track existing keypoints using optical flow and detect new ones if needed.
        """
        # If no tracks, detect fresh ones
        if not self.tracks and self.prev_gray is None:
            corners = cv2.goodFeaturesToTrack(gray_obs, mask=None, **self.feature_params)
            if corners is not None:
                for p in corners:
                    self.tracks.append({'id': self.next_track_id, 'p': p[0]})
                    self.next_track_id += 1
            self.prev_gray = gray_obs
            return
            
        # Track existing with Optical Flow
        p0 = self._get_tracks_arrays()
        if p0 is not None:
            p1, st, err = cv2.calcOpticalFlowPyrLK(self.prev_gray, gray_obs, p0, None, **self.lk_params)
            
            new_tracks = []
            for i, (tr, is_good) in enumerate(zip(self.tracks, st)):
                if is_good[0] == 1:
                    tr['p'] = p1[i][0]
                    new_tracks.append(tr)
            self.tracks = new_tracks
            
        # If we lost too many, detect new ones
        if len(self.tracks) < self.max_landmarks:
            mask = np.ones_like(gray_obs)
            for tr in self.tracks:
                cv2.circle(mask, (int(tr['p'][0]), int(tr['p'][1])), 10, 0, -1) # Mask out existing
            
            new_params = dict(self.feature_params)
            new_params['maxCorners'] = self.max_landmarks - len(self.tracks)
            
            corners = cv2.goodFeaturesToTrack(gray_obs, mask=mask, **new_params)
            if corners is not None:
                for p in corners:
                    self.tracks.append({'id': self.next_track_id, 'p': p[0]})
                    self.next_track_id += 1
                    
        self.prev_gray = gray_obs

    def process_frame(self, event_frame, true_distance=1.0):
        """
        event_frame: 2D numpy array (H, W) uint8, generated by accumulate_events_to_frames.
        true_distance: Since monocular event cameras don't yield depth without complex 
        SLAM/stereo, this adapter takes a dummy OR true proxy depth for the landmarks.
        """
        self.detect_and_track_keypoints(event_frame)
        
        frame_data = {}
        
        # Compute keypoints for ORB extraction
        if not self.tracks:
            self.history.append(frame_data)
            return frame_data
            
        cv_kps = [cv2.KeyPoint(x=float(tr['p'][0]), y=float(tr['p'][1]), size=15) for tr in self.tracks]
        
        # Extract ORB descriptors for the current keypoints
        cv_kps, descs = self.orb.compute(event_frame, cv_kps)
        
        height, width = event_frame.shape[:2]
        
        for i, tr in enumerate(self.tracks):
            # Safe indexing into descriptor array
            if descs is None or i >= len(descs):
                break
                
            u, v = int(tr['p'][0]), int(tr['p'][1])
            if u < 0 or u >= width or v < 0 or v >= height:
                continue
                
            # Compute bearing angle
            # Map u from [0, width] to [-0.5, 0.5] then multiply by FOV
            nx = (u / float(width)) - 0.5
            bearing = nx * (self.fov_x * np.pi / 180.0) # approx horizontal bearing in radians
            
            # Compute 2D vector relative to agent heading 
            d = true_distance
            vec = np.array([d * np.sin(bearing), d * np.cos(bearing)])
            
            frame_data[tr['id']] = {
                'dist': d,
                'bearing': bearing,
                'vector': vec,
                'desc': descs[i].astype(np.float32),
                'pos': (u, v),
            }
            
        self.history.append(frame_data)
        return frame_data

    def process_dataset(self, event_frames, agent_velocities=None, landmark_depths=None):
        """
        Runs the feature tracker over discrete event frames and generates dense arrays for SSP-SLAM.
        
        event_frames: List or Array of (H, W) uint8 frames
        agent_velocities: Array of shape (T, 2) denoting the continuous agent velocity
        landmark_depths: Float or Array of shape (T,) providing depth scalar
        
        Returns:
            velocities: (T, 2)
            vectors: (T, N_landmarks, 2)
            features: (T, N_landmarks, feat_dim)
        """
        T = len(event_frames)
        
        if agent_velocities is None:
            if self.backend == 'gpert':
                from .event_odometry import EventOdometry
                vo = EventOdometry()
            else:
                from .visual_odometry import ORBVisualOdometry
                vo = ORBVisualOdometry()
            estimated_vels = []
            
        # GPERT simulation support
        if self.backend == 'gpert':
            try:
                from .gpert_adapter import SimulatedGPERTAdapter
            except ImportError:
                raise ImportError("gpert backend requires gpert_adapter module (not installed)")
            gpert_adapter = SimulatedGPERTAdapter(max_landmarks=self.max_landmarks, fov_x=self.fov_x)
            
        for t in range(T):
            if self.backend == 'gpert':
                # Pass true depth directly as "simulated depth map" fallback (usually it's a 2D map from simulator)
                # If landmark_depths is passed as a 2D map, send it. If it's a scalar, create a scalar map fallback
                depth_map = landmark_depths[t] if landmark_depths is not None else np.ones_like(event_frames[t], dtype=np.float32)
                # Ensure it's a 2D array since GPERT adapter expects one
                if isinstance(depth_map, (float, int)):
                    depth_map = np.ones_like(event_frames[t], dtype=np.float32) * depth_map
                
                # We append history manually from GPERT adapter since process_dataset loops frames
                frame_data = gpert_adapter.process_frame(event_frames[t], depth_map)
                self.history.append(frame_data)
                
            else:
                depth = 1.0 # arbitrary baseline
                if landmark_depths is not None:
                    depth = landmark_depths[t]
                self.process_frame(event_frames[t], true_distance=depth)
            
            if agent_velocities is None:
                if self.backend == 'gpert':
                    vel, rot = vo.process_frame(event_frames[t])
                    estimated_vels.append([vel[0], vel[2]]) # X and Z
                else:
                    vel, _, _ = vo.process_frame(event_frames[t])
                    estimated_vels.append([vel[0], vel[2]])
                
        # Find which track ids were most stable (seen in most frames)
        track_counts = {}
        for frame in self.history:
            for tid in frame.keys():
                track_counts[tid] = track_counts.get(tid, 0) + 1
                
        # Select top `max_landmarks` most frequently seen keypoints
        sorted_tracks = sorted(track_counts.items(), key=lambda item: item[1], reverse=True)
        top_tracks = [t[0] for t in sorted_tracks[:self.max_landmarks]]
        actual_N = len(top_tracks)
                      
        vel_arr = agent_velocities if agent_velocities is not None else np.array(estimated_vels)
        vec_arr = np.zeros((T, self.max_landmarks, 2))
        feat_arr = np.zeros((T, self.max_landmarks, 32)) 
        
        # Fill arrays
        for t, frame in enumerate(self.history):
            for n_i in range(self.max_landmarks):
                if n_i < actual_N:
                    tid = top_tracks[n_i]
                    if tid in frame:
                        vec_arr[t, n_i] = frame[tid]['vector']
                        feat_arr[t, n_i] = frame[tid]['desc']
                    else:
                        vec_arr[t, n_i] = np.array([self.view_radius * 2, self.view_radius * 2])
                else:
                    vec_arr[t, n_i] = np.array([self.view_radius * 2, self.view_radius * 2])
                    
        return vel_arr, vec_arr, feat_arr
